# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
exclude: '^README.rst$|^tests/|^setup.py$|^examples/|^docs/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 5df1a4bf6f04a1ed3a643167b38d502575e29aef
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: mypy
        name: Run mypy type check
        entry: mypy
        language: system
        args: ["-p", "pipen_verbose"]
        pass_filenames: false
        always_run: true
        files: ^/pipen_verbose/.+$
    -   id: pytest
        name: Run pytest
        entry: pytest
        language: system
        args: [tests/]
        pass_filenames: false
        files: ^tests/.+$|^pipen_verbose/.+$
